version: '3.4'

services:
  private-public:
    build: .
    environment:
      - NODE_ENV=local_node-private
      - AWS_ECS_CLUSTER=ceramic-qa-tests
      - AWS_ECS_FAMILY=ceramic-qa-tests-e2e_tests
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - CLOUDWATCH_LOG_BASE_URL=${CLOUDWATCH_LOG_BASE_URL}
      - DISCORD_WEBHOOK_URL_TEST_FAILURES=${DISCORD_WEBHOOK_URL_TEST_FAILURES}
      - DISCORD_WEBHOOK_URL_TEST_RESULTS=${DISCORD_WEBHOOK_URL_TEST_RESULTS}
      - APIGATEWAY_RESOURCE_ID=${APIGATEWAY_RESOURCE_ID}
      - APIGATEWAY_RESTAPI_ID=${APIGATEWAY_RESTAPI_ID}

  local_client-public:
    build: .
    environment:
      - NODE_ENV=local_node-private
      - AWS_ECS_CLUSTER=ceramic-qa-tests
      - AWS_ECS_FAMILY=ceramic-qa-tests-e2e_tests
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - CLOUDWATCH_LOG_BASE_URL=${CLOUDWATCH_LOG_BASE_URL}
      - DISCORD_WEBHOOK_URL_TEST_FAILURES=${DISCORD_WEBHOOK_URL_TEST_FAILURES}
      - DISCORD_WEBHOOK_URL_TEST_RESULTS=${DISCORD_WEBHOOK_URL_TEST_RESULTS}
      - APIGATEWAY_RESOURCE_ID=${APIGATEWAY_RESOURCE_ID}
      - APIGATEWAY_RESTAPI_ID=${APIGATEWAY_RESTAPI_ID}

  local_node-private:
    build: .
    environment:
      - NODE_ENV=local_node-private
      - AWS_ECS_CLUSTER=ceramic-qa-tests
      - AWS_ECS_FAMILY=ceramic-qa-tests-e2e_tests
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - CLOUDWATCH_LOG_BASE_URL=${CLOUDWATCH_LOG_BASE_URL}
      - DISCORD_WEBHOOK_URL_TEST_FAILURES=${DISCORD_WEBHOOK_URL_TEST_FAILURES}
      - DISCORD_WEBHOOK_URL_TEST_RESULTS=${DISCORD_WEBHOOK_URL_TEST_RESULTS}
      - APIGATEWAY_RESOURCE_ID=${APIGATEWAY_RESOURCE_ID}
      - APIGATEWAY_RESTAPI_ID=${APIGATEWAY_RESTAPI_ID}
