name: Build and Push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Dagger
  DAGGER_PLAN: cue.mod/pkg/github.com/3box/pipeline-tools/ci/e2e.cue
  DAGGER_LOG_FORMAT: "plain"
  PIPELINE_TOOLS_VER: "0.2.1"

jobs:
  run:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Install Dagger
      uses: dagger/dagger-for-github@v3
      with:
        install-only: true
    -
      name: Setup Dagger
      run: |
        dagger project init
        dagger project update
        dagger project update "github.com/3box/pipeline-tools@v${{ env.PIPELINE_TOOLS_VER }}"
    -
      name: Push Docker image
      run: dagger do push -w "actions:push:\"${{ env.AWS_REGION }}\":\"${{ env.SHA }}\":\"${{ env.SHA_TAG }}\":_" -p ${{ env.DAGGER_PLAN }}
