on:
  workflow_dispatch:
    inputs:
      tests:
        description: "Space separated list of tests to run. Runs all available by default."
        required: false
        default: 'smoke'

name: Run Tests on ECS

jobs:
  run_ecs_tasks:
    name: Run ECS Task
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - smoke_test_config: "internal-external"
          - smoke_test_config: "local_client-external"
          - smoke_test_config: "local_node-internal"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Run smoke tests
      if: contains('smoke', github.event.inputs.tests)
      run: |
        aws ecs run-task \
          --cluster ceramic-dev-tests \
          --task-definition ceramic-dev-tests-smoke_tests \
          --launch-type FARGATE \
          --network-configuration ${{ secrets.NETWORK_CONFIGURATION }} \
          --overrides { "containerOverrides": [{ "environment": [{ "name": "NODE_ENV", "value": "${{ matrix.smoke_test_config }}" }] }] }
