on:
  schedule:
  - cron: "0 0/8 * * *" # Every 8 hours
  workflow_dispatch:

env:
  # Dagger
  DAGGER_PLAN: cue.mod/pkg/github.com/3box/pipeline-tools/ci/plans/tests.cue
  DAGGER_LOG_FORMAT: "plain"
  PIPELINE_TOOLS_VER: "0.2.0"
  # Secrets
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

name: Run Tests on ECS

jobs:
  run_ecs_tasks:
    name: Run ECS Task
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Install Dagger
      uses: dagger/dagger-for-github@v3
      with:
        install-only: true
    -
      name: Setup Dagger
      run: |
        dagger project init
        dagger project update
        dagger project update "github.com/3box/pipeline-tools@v${{ env.PIPELINE_TOOLS_VER }}"
    -
      name: Run integration tests
      run: dagger do -l error test -w "actions:test:\"${{ secrets.AWS_REGION }}\":qa:test_e2e:_" -p ${{ env.DAGGER_PLAN }}
