on:
  schedule:
  - cron: "0 0/8 * * *" # Every 8 hours
  workflow_dispatch:
    inputs:
      tests:
        description: "Space separated list of tests to run. Runs all available by default."
        required: false
        default: 'e2e'

name: Run Tests on ECS

jobs:
  run_ecs_tasks:
    name: Run ECS Task
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - e2e_test_config: "private-public"
          - e2e_test_config: "local_client-public"
          - e2e_test_config: "local_node-private"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Run integration tests
      if: contains('e2e', github.event.inputs.tests)
      run: |
        aws ecs run-task \
          --cluster ceramic-qa-tests \
          --task-definition ceramic-qa-tests-e2e_tests \
          --launch-type FARGATE \
          --network-configuration ${{ secrets.NETWORK_CONFIGURATION }} \
          --enable-execute-command \
          --overrides '{ "containerOverrides": [{ "name": "e2e_tests", "environment": [{ "name": "NODE_ENV", "value": "${{ matrix.e2e_test_config }}" }, { "name": "AWS_ACCESS_KEY_ID", "value": "${{ secrets.S3_AWS_ACCESS_KEY_ID }}" }, { "name": "AWS_SECRET_ACCESS_KEY", "value": "${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}" }, { "name": "AWS_REGION", "value": "${{ secrets.S3_AWS_REGION }}" }, { "name": "ETH_RPC_URL", "value": "${{ secrets.ETH_RPC_URL }}" }] }] }'
